select ZRECORD.ZIDENTIFIER MozeId, ZRECORD.ZNAME DealName, ZRECORD.ZDATE Date, ZRECORD.ZTIME Time, ZRECORD.ZPRICE Amount, c.ZIMAGE Bigtype, c.ZNAME SmallType, p.ZNAME Project, t.ZNAME PaymentType
from ZRECORD
left join ZCLASSIFICATION c on (ZRECORD.ZCLASSIFICATION=c.ZIDENTIFIER)
left join ZPROJECT p on (ZRECORD.ZPROJECTID = p.ZIDENTIFIER)
left join ZTRANSACTIONTYPE t on (ZRECORD.ZTRANSACTIONTYPE = t.ZIDENTIFIER)